### PR TITLE
Fix support_energy_consumption

### PR DESCRIPTION
**Pull request by jwillemsen**
* custom_components/daikin_residential_altherma/daikin_base.py:

### CODE REVIEW

**Comment by jwillemsen** [comment]
See https://github.com/rospogrigio/daikin_residential/commit/1df22730954bd1e49f637545089ae016a9a674ba

**Comment by speleolontra** [comment]
Hi @jwillemsen ,
I've tested this pull request but for me 
`self.getData(ATTR_ENERGY_CONSUMPTION)`
return "None" in place of "True". 
Maybe any error in config, i need tume to verify...
Have you the same result?
Thanks!

**Comment by jwillemsen** [comment]
Will try to retest this week, closing for the moment

**Comment by jwillemsen** [comment]
Ok, you are correct, this doesn't work, looks the way the energy values are handled are different between the two integrations, not sure why, closing for this moment

**Pull request closed without merging**
