### PR TITLE
Use EntityCategory to fix problems with HA 2022.4

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by jwillemsen** [comment]
This is not tested yet, looking for testers ;-)

**Comment by MicheleMercuri** [comment]
Ok just tested and i's works again. many thanks [jwillemsen](https://github.com/jwillemsen)

**Comment by jwillemsen** [comment]
Fixes #48

**Comment by speleolontra** [comment]
Great Work @jwillemsen .
Thanks.

**Pull request merged**
