### PR TITLE
Full sensor rework

### PR DESCRIPTION
**Pull request by jwillemsen**
This PR adds support to read all sensors from the Altherma but also regular Daikin AC devices back to HA. This will break existing automations as all IDs are changed, this is still in progress work!

### CODE REVIEW

**Comment by mp3guy** [comment]
Does this create redundancy with https://github.com/rospogrigio/daikin_residential?

**Comment by jwillemsen** [comment]
Goal is to provide full support for altherma and non-altherma Daikin devices, https://github.com/rospogrigio/daikin_residential isn't updated now for a long time, I have a huge amount of PRs outstanding there which are not integrated at all. With the rework I am doing it should be much easier and straight forward to support the various AC models. All sensors already work, need to rework the control operations for the altherma

**Comment by jwillemsen** [comment]
Yes, I am also using both, I have permissions to merge/release in this project, but not in rospogrigio, don't want to wait any longer on him to review my PRs, with the rework I am doing adding support for the AC units is some work, but it will also make it possible for me to use one integration.

**Comment by jwillemsen** [comment]
Part of #205

**Pull request closed without merging**
